#!/usr/bin/env python3
"""
Regenerate assets/tutors.js from the tutor assignment spreadsheet.

Usage:
    python3 tools/generate_tutors.py tutors.csv > assets/tutors.js

The CSV must have a header row and contain (at least) these columns:
    e-mail        -> the tutor's login email
    New Courses   -> semicolon-separated list containing the course codes
                     [2058] / [2059] / [2060] / [2063]

Emails are stored as djb2 hashes (base36) so the raw address list is not
readable in the published page. Courses are stored as a bitmask.
"""
import csv, re, sys, json

BITS = {"2058": 1, "2059": 2, "2060": 4, "2063": 8}

def h(s):
    x = 5381
    for ch in s:
        x = ((x << 5) + x + ord(ch)) & 0xFFFFFFFF
    return x

def main(path):
    out = {}
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            email = (row.get("e-mail") or "").strip().lower()
            if "@" not in email:
                continue
            mask = 0
            for code in re.findall(r"\d{4}", row.get("New Courses") or ""):
                mask |= BITS.get(code, 0)
            if mask:
                out[format(h(email), "x")] = mask
    sys.stdout.write("// AUTO-GENERATED by tools/generate_tutors.py — do not edit by hand.\n")
    sys.stdout.write("// %d tutors. Bitmask: 1=2058, 2=2059, 4=2060, 8=2063\n" % len(out))
    sys.stdout.write("window.TUTORS=" + json.dumps(out, separators=(",", ":")) + ";\n")

if __name__ == "__main__":
    main(sys.argv[1])
